### ISSUE TITLE
Checking for overlapping ships on placement

### ISSUE THREAD

**Issue by justinTM** [cs361fall2018/project-team-31#11]
When a new ship is placed, a check needs to be performed to make sure no grid space has more than one ship in it.

I have no idea how to do this... Do we get the coordinates from when the user clicks the mouse, then check if that coordinate has a ship?

**Comment by Evdemonm** [comment]
I honestly have no idea on how the mouse click thing works, but I have an idea on how to write the function so it detects a ship or at least something else in that designated square.

**Comment by justinTM** [comment]
> I have an idea on how to write the function so it detects a ship or at least something else in that designated square

@Evdemonm, what do you have in mind?

**Comment by justinTM** [comment]
this won't be done by Sprint 1, because I changed my User Story to get the `occupiedSpaces` setting/getting/clearing working, instead.

@Evdemonm 
@caiusb 
@iKiwiz 
@manideepa03
