### ISSUE TITLE
We need a way to have the occupied squares be set to the board after a ship is placed

### ISSUE THREAD

**Issue by Evdemonm** [cs361fall2018/project-team-31#12]
I have a pretty good idea on how to do this, but I will start working on testing for this and then coding it into the ship function. This will involve the setoccupiedsquare and getoccupiedsquare function. When the get function is called a loop for( square TEST : occupiedsquare) along with add should be able to get it the occupied squares into the board.

**Comment by justinTM** [comment]
ayyy I think I figured it out! Take a look at #25, which I think satisfies this issue?

**Comment by justinTM** [comment]
#30 has updated code. @Evdemonm can you review it and see if we can close this?
