### ISSUE TITLE
A function needs to be added to the Ships class to act as an accessor for a private variable

### ISSUE THREAD

**Issue by Evdemonm** [cs361fall2018/project-team-31#5]
The one function `ship(kind)` will get a variable `length`, that `length` variable needs to be accessed even though it is a private, an accessor function is needed

**Comment by justinTM** [comment]
> The one function ship(kind) will get a variable length

From Ship.java:
```
@JsonProperty private List<Square> occupiedSquares;
@JsonProperty private String Type;
@JsonProperty private int s;
```

@Evdemonm Is "`length`" mean the `private int s`? Or is `length` gonna be a new variable?

**Comment by Evdemonm** [comment]
> > The one function ship(kind) will get a variable length
> 
> From Ship.java:
> 
> ```
> @JsonProperty private List<Square> occupiedSquares;
> @JsonProperty private String Type;
> @JsonProperty private int s;
> ```
> @Evdemonm Does "`length`" mean the `private int s`? Or is `length` gonna be a new variable?

The length should be saved as s so it can be used to help place the ships. Length will not be it's own a variable, but s can be changed to be length if that would make more sense. I have finished this part and keeping the boat placement withing boundaries. I am currently working on actually placing them in so they do not overlap with one another.
