### ISSUE TITLE
Creating Captain's Quarters

### ISSUE THREAD

**Issue by iKiwiz** [cs361fall2018/project-team-31#54]
needs a way to keep track of the captain's quarters, its correct placement, implementation of "armor" on battleships and destroyers and sinking ship if hit twice, or if hit once on minesweepers

**Comment by justinTM** [comment]
Made some changes to the new Ship subclasses, where I put the `captains_quarters` variable inside the superclass `Ship`.

**Comment by Evdemonm** [comment]
added an attack function

**Comment by justinTM** [comment]
See #64 for attack function. Disregard my [earlier comment](https://github.com/cs361fall2018/project-team-31/issues/54#issuecomment-437490495).
